export const flashSaleProducts = [
  {
    id: 1,
    title: "Men's Classic Fit Dress Shirt",
    price: 39.99,
    oldPrice: 69.99,
    discount: 43,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.5,
    reviews: 127,
    stock: 15,
    tag: "Official Store",
    express: true,
    category: "clothing",
    subCategory: "men",
    description: "A classic fit dress shirt made from premium cotton with wrinkle-resistant finish, perfect for professional settings."
  },
  {
    id: 2,
    title: "Women's Casual Maxi Dress",
    price: 49.99,
    oldPrice: 79.99,
    discount: 38,
    image: "https://images.unsplash.com/photo-1495385794356-15371f348c31?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.8,
    reviews: 342,
    stock: 23,
    tag: "Official Store",
    express: true,
    category: "women clothing",
    subCategory: "women",
    description: "Elegant and comfortable maxi dress with floral pattern, perfect for summer days and casual outings."
  },
  {
    id: 3,
    title: "Children's Colorful T-Shirt Set",
    price: 24.99,
    oldPrice: 34.99,
    discount: 29,
    image: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.3,
    reviews: 89,
    stock: 8,
    tag: "Limited Stock",
    express: true,
    category: "accessories",
    subCategory: "children",
    description: "Set of 3 colorful cotton t-shirts for children, featuring fun graphics and comfortable fit."
  },
  {
    id: 4,
    title: "Men's Running Shoes",
    price: 89.99,
    oldPrice: 129.99,
    discount: 31,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.6,
    reviews: 215,
    stock: 42,
    tag: "Best Seller",
    express: true,
    category: "shoes",
    subCategory: "men",
    description: "Lightweight running shoes with responsive cushioning and breathable mesh upper for maximum comfort during workouts."
  },
  {
    id: 5,
    title: "Women's Heeled Sandals",
    price: 59.99,
    oldPrice: 89.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.2,
    reviews: 178,
    stock: 37,
    tag: "Summer Style",
    express: false,
    category: "shoes",
    subCategory: "women",
    description: "Elegant heeled sandals with ankle strap, perfect for evening events and special occasions."
  },
  {
    id: 6,
    title: "Kids' Light-up Sneakers",
    price: 34.99,
    oldPrice: 49.99,
    discount: 30,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.7,
    reviews: 203,
    stock: 19,
    tag: "Kids Favorite",
    express: true,
    category: "shoes",
    subCategory: "children",
    description: "Fun light-up sneakers for kids with durable soles and easy velcro closure, making them perfect for active children."
  }
];

export const featuredProducts = [
  {
    id: 7,
    title: "Men's Leather Jacket",
    price: 149.99,
    oldPrice: 199.99,
    discount: 25,
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.4,
    reviews: 156,
    stock: 28,
    tag: "Editor's Choice",
    express: true,
    category: "clothing",
    subCategory: "men",
    description: "Classic leather jacket with quilted lining, perfect for adding a stylish edge to any casual outfit."
  },
  {
    id: 8,
    title: "Women's Winter Coat",
    price: 119.99,
    oldPrice: 179.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.9,
    reviews: 278,
    stock: 12,
    tag: "Winter",
    express: true,
    category: "clothing",
    subCategory: "women",
    description: "Warm and stylish winter coat with faux fur trim hood, designed to keep you cozy in cold weather."
  },
  {
    id: 9,
    title: "Children's Dinosaur Pajamas",
    price: 19.99,
    oldPrice: 29.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1617464529340-52661d3ca547?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.3,
    reviews: 132,
    stock: 31,
    tag: "Bedtime Favorite",
    express: false,
    category: "clothing",
    subCategory: "children",
    description: "Soft and cozy pajama set with fun dinosaur print, perfect for ensuring a comfortable night's sleep."
  },
  {
    id: 10,
    title: "Men's Formal Oxford Shoes",
    price: 99.99,
    oldPrice: 149.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.5,
    reviews: 167,
    stock: 45,
    tag: "Formal",
    express: true,
    category: "shoes",
    subCategory: "men",
    description: "Classic Oxford shoes crafted from genuine leather with a polished finish, ideal for formal occasions."
  },
  {
    id: 11,
    title: "Women's Comfortable Flats",
    price: 49.99,
    oldPrice: 69.99,
    discount: 29,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.7,
    reviews: 195,
    stock: 14,
    tag: "Everyday",
    express: true,
    category: "shoes",
    subCategory: "women",
    description: "Comfortable ballet flats with cushioned insole, perfect for everyday wear and walking comfort."
  },
  {
    id: 12,
    title: "Kid's Waterproof Rain Boots",
    price: 29.99,
    oldPrice: 44.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.8,
    reviews: 231,
    stock: 9,
    tag: "Rainy Day",
    express: false,
    category: "shoes",
    subCategory: "children",
    description: "Colorful waterproof rain boots for kids with easy-grip handles to help them put them on independently."
  }
];

export const popularProducts = [
  {
    id: 13,
    title: "Men's Slim Fit Jeans",
    price: 59.99,
    oldPrice: 79.99,
    discount: 25,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.4,
    reviews: 122,
    stock: 26,
    tag: "Classic",
    express: true,
    category: "clothing",
    subCategory: "men",
    description: "Slim fit jeans made from premium denim with slight stretch for comfort and everyday wear."
  },
  {
    id: 14,
    title: "Women's Yoga Pants",
    price: 39.99,
    oldPrice: 59.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1556068791-9d6ba2cb5bba?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.6,
    reviews: 287,
    stock: 38,
    tag: "Fitness",
    express: true,
    category: "clothing",
    subCategory: "women",
    description: "High-waisted yoga pants with 4-way stretch and hidden pocket, perfect for yoga, gym, or casual wear."
  },
  {
    id: 15,
    title: "Children's School Uniform Set",
    price: 44.99,
    oldPrice: 64.99,
    discount: 31,
    image: "https://images.unsplash.com/photo-1611858346982-5a238d3d4308?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.2,
    reviews: 143,
    stock: 22,
    tag: "School",
    express: false,
    category: "clothing",
    subCategory: "children",
    description: "Complete school uniform set including shirt, pants/skirt, and tie, made from durable, easy-care fabric."
  },
  {
    id: 16,
    title: "Men's Casual Loafers",
    price: 69.99,
    oldPrice: 99.99,
    discount: 30,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.3,
    reviews: 176,
    stock: 34,
    tag: "Casual",
    express: true,
    category: "shoes",
    subCategory: "men",
    description: "Slip-on loafers with memory foam insole for supreme comfort, ideal for casual and business casual settings."
  },
  {
    id: 17,
    title: "Women's Ankle Boots",
    price: 79.99,
    oldPrice: 119.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1519415387722-a1c3bbef716c?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.5,
    reviews: 209,
    stock: 47,
    tag: "Trendy",
    express: true,
    category: "shoes",
    subCategory: "women",
    description: "Stylish ankle boots with stacked heel and side zipper, versatile for pairing with jeans, dresses, or skirts."
  },
  {
    id: 18,
    title: "Kids' Sport Sandals",
    price: 24.99,
    oldPrice: 34.99,
    discount: 29,
    image: "https://images.unsplash.com/photo-1617796110716-266702087e09?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.7,
    reviews: 183,
    stock: 16,
    tag: "Summer",
    express: false,
    category: "shoes",
    subCategory: "children",
    description: "Durable sport sandals for kids with quick-dry straps and non-slip soles, perfect for summer adventures."
  },
  {
    id: 19,
    title: "Kids' Sport Sandals",
    price: 24.99,
    oldPrice: 30.99,
    discount: 29,
    rating: 4.7,
    reviews: 183,
    stock: 16,
    tag: "Summer",
    express: false,
    category: "bags",
    subCategory: "children",
    description: "Durable sport sandals for kids with quick-dry straps and non-slip soles, perfect for summer adventures.",
    image: 'https://plus.unsplash.com/premium_photo-1673384389924-097135cbf1cd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZGVzaWduZXIlMjBiYWd8ZW58MHx8MHx8fDA%3D'
  }
];

export const topSellingProducts = [
  {
    id: 20,
    title: "Men's Polo Shirt",
    price: 29.99,
    oldPrice: 44.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.8,
    reviews: 312,
    stock: 11,
    tag: "Essential",
    express: true,
    category: "clothing",
    subCategory: "men",
    description: "Classic polo shirt made from soft cotton piqué with ribbed collar and cuffs for a polished casual look."
  },
  {
    id: 21,
    title: "Children's Hooded Sweatshirt",
    price: 24.99,
    oldPrice: 34.99,
    discount: 29,
    image: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.7,
    reviews: 268,
    stock: 7,
    tag: "Cozy",
    express: false,
    category: "clothing",
    subCategory: "children",
    description: "Warm and comfortable hooded sweatshirt with kangaroo pocket, ideal for chilly days and active play."
  },
  {
    id: 22,
    title: "Men's Hiking Boots",
    price: 99.99,
    oldPrice: 149.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1588361861040-ac9b1018f6d5?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.4,
    reviews: 192,
    stock: 15,
    tag: "Outdoor",
    express: true,
    category: "shoes",
    subCategory: "men",
    description: "Waterproof hiking boots with rugged outsole for excellent traction on varied terrain and padded collar for ankle support."
  },
  {
    id: 23,
    title: "Women's Running Sneakers",
    price: 79.99,
    oldPrice: 109.99,
    discount: 27,
    image: "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.5,
    reviews: 217,
    stock: 41,
    tag: "Fitness",
    express: true,
    category: "shoes",
    subCategory: "women",
    description: "Lightweight running sneakers with responsive cushioning and breathable mesh for comfort during long runs."
  },
  {
    id: 24,
    title: "Kids' School Shoes",
    price: 39.99,
    oldPrice: 59.99,
    discount: 33,
    image: "https://images.unsplash.com/photo-1507464098880-e367bc5d2c08?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.6,
    reviews: 187,
    stock: 25,
    tag: "School",
    express: false,
    category: "shoes",
    subCategory: "children",
    description: "Durable school shoes with scuff-resistant toe cap and non-marking soles, designed to withstand playground activities."
  }
];

export const clearanceProducts = [
  {
    id: 25,
    title: "Men's Summer Shorts",
    price: 19.99,
    oldPrice: 39.99,
    discount: 50,
    image: "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.3,
    reviews: 156,
    stock: 5,
    tag: "Clearance",
    express: true,
    category: "clothing",
    subCategory: "men",
    description: "Lightweight cotton shorts with comfortable elastic waistband and side pockets, ideal for warm weather."
  },
  {
    id: 26,
    title: "Women's Sun Dress",
    price: 24.99,
    oldPrice: 49.99,
    discount: 50,
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.2,
    reviews: 138,
    stock: 8,
    tag: "Clearance",
    express: true,
    category: "clothing",
    subCategory: "women",
    description: "Flowy sundress with adjustable straps and floral print, perfect for summer days and beach vacations."
  },
  {
    id: 27,
    title: "Children's Graphic T-Shirts",
    price: 9.99,
    oldPrice: 19.99,
    discount: 50,
    image: "https://images.unsplash.com/photo-1519278409-1f56fdda7fe5?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.5,
    reviews: 124,
    stock: 13,
    tag: "Clearance",
    express: false,
    category: "clothing",
    subCategory: "children",
    description: "Set of 2 cotton graphic t-shirts with fun, colorful designs that kids will love, made from soft, breathable fabric."
  },
  {
    id: 28,
    title: "Men's Canvas Sneakers",
    price: 19.99,
    oldPrice: 39.99,
    discount: 50,
    image: "https://images.unsplash.com/photo-1527010154944-f2241763d806?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.1,
    reviews: 103,
    stock: 32,
    tag: "Clearance",
    express: true,
    category: "shoes",
    subCategory: "men",
    description: "Classic canvas sneakers with rubber sole, providing casual style and comfort for everyday wear."
  },
  {
    id: 29,
    title: "Women's Summer Sandals",
    price: 14.99,
    oldPrice: 29.99,
    discount: 50,
    image: "https://images.unsplash.com/photo-1565537222174-2a43cdeab175?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.4,
    reviews: 167,
    stock: 29,
    tag: "Clearance",
    express: true,
    category: "shoes",
    subCategory: "women",
    description: "Stylish flat sandals with decorative straps and cushioned footbed, perfect for summer outfits."
  },
  {
    id: 30,
    title: "Kids' Canvas Slip-ons",
    price: 12.99,
    oldPrice: 25.99,
    discount: 50,
    image: "https://images.unsplash.com/photo-1531907700752-62799b2a3e84?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.3,
    reviews: 145,
    stock: 24,
    tag: "Clearance",
    express: false,
    category: "shoes",
    subCategory: "children",
    description: "Easy slip-on canvas shoes for kids with elastic side panels for easy on and off, available in fun patterns."
  },

  {
    id: 31,
    title: "Women's Blazer",
    price: 89.99,
    oldPrice: 129.99,
    discount: 31,
    image: "https://images.unsplash.com/photo-1591992505936-d2a2d6618a7e?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    rating: 4.6,
    reviews: 245,
    stock: 19,
    tag: "Office",
    express: true,
    category: "clothing",
    subCategory: "women",
    description: "Tailored blazer with subtle stretch for comfort, perfect for elevating both office and casual outfits."
  },

];

export const categories = [
  {
    id: 32,
    title: "Women's Clothing",
    image: "https://images.unsplash.com/photo-1551048632-c72a365e5f97?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "clothing",
    subCategory: "women",
    price: 210,
    stock: 12,
    reviews: 215,
    icon: "https://cdn-icons-png.flaticon.com/512/2933/2933113.png", // T-shirt icon for clothing
  },
  {
    id: 33,
    title: "Shoes",
    image: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "shoes",
    subCategory: "men",
    price: 103,
    stock: 19,
    reviews: 215,
    icon: "https://cdn-icons-png.flaticon.com/512/2589/2589903.png",// Shoe icon for men's shoes
  },
  {
    id: 34,
    title: "Women's Shoes",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "shoes",
    subCategory: "women",
    price: 310,
    stock: 12,
    reviews: 215,
    icon: "https://cdn-icons-png.flaticon.com/512/2964/2964267.png", // Shoe icon for women's shoes
  },
  {
    id: 35,
    title: "Bags",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "bags",
    price: 109,
    stock: 34,
    reviews: 215,
    icon: "https://cdn-icons-png.flaticon.com/512/1063/1063376.png", // Bag or accessories icon
  },
  {
    id: 36,
    title: "Clothing",
    image: "https://images.unsplash.com/photo-1617196701537-7329482cc9fe?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "clothing",
    subCategory: "men",
    price: 110,
    stock: 20,
    reviews: 215,
    icon: "https://cdn-icons-png.flaticon.com/512/1785/1785255.png", // T-shirt icon for clothing
  },
];